---
- name: Install SonarQube on Ubuntu 22.04
  hosts: sonarqube  
  become: true
  tasks:
    - name: install java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: install postgresql
      apt:
        name: postgresql postgresql-contrib
        state: present  

    - name: Start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL user and database for SonarQube
      become_user: postgres
      postgresql_db:
        name: sonar
        encoding: UTF8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        template: template0
        state: present

    - name: Create PostgreSQL user for SonarQube
      become_user: postgres
      postgresql_user:
        name: sonar
        password: "sonar"
        state: present

    - name: Grant privileges to SonarQube user on database
      become_user: postgres
      postgresql_privs:
        db: sonar
        role: sonar
        privs: ALL
        type: database

    - name: Download SonarQube binary
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip
        dest: /opt/sonarqube.zip
      vars:
        sonarqube_version: 10.5.1  # Adjust to desired version

    - name: Extract SonarQube archive
      archive:
        path: /opt/sonarqube.zip
        dest: /opt/sonarqube
        extract: yes
        owner: sonarqube
        group: sonarqube
      vars:
        sonarqube_user: sonarqube  # Adjust username if needed

    - name: Create SonarQube system user
      user:
        name: "{{ sonarqube_user }}"
        system: yes
        shell: /bin/bash  # Adjust shell if needed

    - name: Create systemd service file for SonarQube
      template:
        src: sonarqube.service.j2
        dest: /etc/systemd/system/sonar.service
        owner: root
        group: root
      vars:
        sonarqube_home: /opt/sonarqube

    - name: Reload systemd daemon
      systemd:
        name: daemon-reload

    - name: Enable SonarQube service at boot
      systemd:
        name: sonar.service#
        
        enabled: yes

    - name: Restart SonarQube service
      service:
        name: sonar
        state: restarted

