- name: update apt
  apt:
    update_only: yes
    update_cache: yes
- name: install postgresql
  apt:
    name: postgresql postgresql-contrib
    state: present  
- name: Start PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes
- name: Create PostgreSQL user and database for SonarQube
  become_user: postgres
  postgresql_db:
    name: sonar
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
- name: Create PostgreSQL user for SonarQube
  become_user: postgres
  postgresql_user:
    name: sonar
    password: "sonar"
    state: present
- name: Grant privileges to SonarQube user on database
  become_user: postgres
  postgresql_privs:
    db: sonar
    role: sonar
    privs: ALL
    type: database